# Generated by Django 4.1.7 on 2023-03-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empanada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empanada', models.CharField(max_length=20)),
                ('precio_empanada', models.IntegerField()),
                ('coccion_empanada', models.CharField(max_length=100)),
                ('sabor_empanada', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pizza', models.CharField(max_length=20)),
                ('precio_pizza', models.IntegerField()),
                ('descripcion_pizza', models.CharField(max_length=100)),
                ('tamanio_pizza', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='bebida',
            name='litros_bebida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='precio_bebida',
            field=models.IntegerField(),
        ),
    ]
